name: flutter_flame_playground
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0

  # Extend
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^4.0.0

  # Build Runner
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
